version: '3.8'

services:
  front:
    build:
      context: ./soa-lab-3-front
    ports:
      - "3000:3000"
    depends_on:
      - main-service
      - grammy-service
    networks:
      - soa-network
  
  db:
    image: postgres:15
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
    networks:
      - soa-network
    command: ["postgres", "-c", "log_statement=all", "-c", "timezone=UTC"]

  main-service-ejb:
    build: 
      context: .
      dockerfile: ./soa-lab-3-back/main-service/ejb-module/Dockerfile
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - db
    networks:
      - soa-network

  main-service:
    build:
      context: ./soa-lab-3-back/main-service/service
    ports:
      - "1111:1111"
    environment:
      SERVER_SSL_ENABLED: true
      SERVER_SSL_KEY_STORE: classpath:static/server.keystore.p12
      SERVER_SSL_KEY_STORE_PASSWORD: DashaYana
      SERVER_SSL_KEY_ALIAS: main-server
    depends_on:
      - db
      - main-service-ejb
    networks:
      - soa-network


  grammy-service:
    build:
      context: ./soa-lab-3-back/grammy-service
    ports:
      - "1112:1112"
    depends_on:
      - db
      - main-service
    networks:
      - soa-network

networks:
  soa-network:
    driver: bridge
