server:
  port: 1112
  ssl:
    enabled: true
    key-store: classpath:static/server.keystore.p12
    key-store-password: DashaYana
    key-store-type: PKCS12
    key-alias: main-server

trust:
  store:
    url: classpath:static/server.keystore.p12
    password: DashaYana

spring:
  application:
    name:
      grammy-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    enabled: false
    service-url:
      #        defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-service:8761/eureka/

main-service:
  ribbon:
    listOfServers: main-service-1:1111, main-service-2:1111
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    eureka:
      enabled: false
    ServerListRefreshInterval: 100
    retryableStatusCodes: 500
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
    ReadTimeout: 10000
    ConnectTimeout: 10000
    EnablePrimeConnections: true

ribbon:
  eureka:
    enabled: false

zuul:
  ignored-services: "*"
  ribbon-isolation: thread
  retryable: true
  routes:
    main-service:
      path: '/api/v1/grammy/**'
      serviceId: main-service
      stripPrefix: false
      retryable: true
    retryable: true

